version: '3.7'

services:
  db:
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - 5432:5432
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - IS_COMPOSE=true
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    env_file:
      - ./.env
